### ISSUE TITLE
大数量调用问题

### ISSUE THREAD

**Issue by shang7053** [lindzh/rpc#2]
我看介绍说不支持返回数据量超大的调用（压缩后超过1m）。那假如我做一个导出，需要一次性返回大量数据，这个怎么解决？那个1m有地方可以配置吗？

**Comment by lindzh** [comment]
压缩后的1m其实很大了，一般几十个字段的对象1000个压缩后都不到512kb，能适配大量场景下问rpc调用，返回数据量超大的情况，性能影较大。如果有特殊的文件下载这样的返回数据压缩后还很大，不建议使用rpc

**Comment by shang7053** [comment]
原来是这样，我倒没有具体是测过数据占用多大空间，不过照你这么说，我的场景是三个字段为一条数据，一万条数据，应该还在可接受范围内。多谢了，很好的rpc，有机会在项目里用下
